[workspace]
members = [
    "crates/lindar-core",
    "crates/lindar-protocol",
    "crates/lindar-network",
    "apps/lindard",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.75"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
mdns-sd = "0.13.10"
gethostname = "1"
uuid = { version = "1", features = ["v4"] }
