[package]
name = "lindard"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
lindar-core = { path = "../../crates/lindar-core" }
lindar-network = { path = "../../crates/lindar-network" }
lindar-protocol = { path = "../../crates/lindar-protocol" }
gethostname.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3"
